name: QA Workflow

on:
  push:
    # Push events
    branches:
      - master
  workflow_dispatch:
  pull_request:
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen gcovr lcov cppcheck graphviz clang-format valgrind bc cmake gcc g++ libmicrohttpd-dev python3 doxygen
          version: 1.0

      - name: Run style check
        uses: ./.github/actions/style

      - name: Run documentation check
        uses: ./.github/actions/documentation

      - name: Build project
        uses: ./.github/actions/building

      - name: Run tests and coverage
        uses: ./.github/actions/coverage_and_test

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Verify documentation generation
        run: test -d ./documentation

      - name: Compress documentation directory
        run: tar -czvf doxygen_docs.tar.gz ./documentation

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Doxygen-Docs
          path: doxygen_docs.tar.gz
